### PR TITLE
[CALCITE-1520] Implement isValid for AvaticaConnection

### PR DESCRIPTION
**Pull request by risdenk**
* Changed helper to a static variable on the connection so Mockito could instantiate it. Since the underlying helper INSTANCE is static, I didn't think this would be an issue. Most of the line changes come from fixing Checkstyle for static final variable being uppercase.
* Implemented isValid without fully checking the underlying connection is actually valid. Does check if the connection is closed.
* Added test for isValid for negative timeout and isClosed checks.

There didn't seem to be a way to check if there is a valid connection to the Avatica server. I thought about adding to the service or trying to get to the underlying HttpClient. However, none of these expose a timeout that would be reasonable. This implementation although not complete is a start in the right direction.

### CODE REVIEW

**Comment by joshelser** [comment]
Change looks good to me, @risdenk.

My only ask would be if you could add a test case to `RemoveDriverTest` in the server module? Something simple/high-level that doesn't rely on mocking (e.g. create a connection, use it, check `isValid`, close the connection, ensure `isValid() == false`.

**Comment by risdenk** [comment]
Sure will add that today hopefully

**Comment by risdenk** [comment]
@joshelser - thanks for the quick review. Added a test case to `RemoteDriverTest`

**Comment by risdenk** [comment]
Looks like the test failure is related to JDK7 and bumping the hsqldb version?

**Comment by joshelser** [comment]
Yeah, not your problem. Will try to merge this sucka in today. Thanks for the PR!

**Pull request closed without merging**
