### PR TITLE
[CALCITE-2845] Avoid duplication of exception messages

### PR DESCRIPTION
**Pull request by vlsi**
https://issues.apache.org/jira/browse/CALCITE-2845

### CODE REVIEW

**Comment by vlsi** [comment]
@joshelser , @risdenk , this PR passes all the tests, and it makes exceptions more readable.
I'm inclined to merge the change. Any thoughts / objections?

**Comment by apilloud** [comment]
This change introduces a regression. Details of an exception are dropped in most JDBC clients, as they don't display the full stack trace. I've opened an issue: https://issues.apache.org/jira/browse/CALCITE-3040

**Comment by vectorijk** [comment]
It blocks us for upgrading the version. Fix it in a minor version (1.14.1) release could work for us.
looking at the bug.

**Comment by vlsi** [comment]
I would rather thread it as a SQL client bug.

**Pull request merged**
