### PR TITLE
[CALCITE-5803] Migrate Avatica to Gradle 8.1.1

### PR DESCRIPTION
**Pull request by richardantal**

### CODE REVIEW

**Comment by snuyanzin** [comment]
i wonder if there is anything blocking movement to 8.1.1?

**Comment by richardantal** [comment]
@snuyanzin Can you please review this change or do you know who should I ask?

**Comment by snuyanzin** [comment]
i will try to have a look today by the end of the day

**Comment by snuyanzin** [comment]
It looks ok from my side

the thing I noticed is that `./gradlew tasks` is failing... 
however I checked that it also fails with 7.6.1, so probably `./gradlew tasks` could be done in a follow up task

**Review by snuyanzin — APPROVED** [review]

**Comment by snuyanzin** [comment]
i will merge it soon
thanks @richardantal

**Comment by richardantal** [comment]
Thank you for the review @snuyanzin 

I created https://issues.apache.org/jira/browse/CALCITE-5812 to track the ./gradlew tasks problem

**Pull request merged**
