### PR TITLE
[CALCITE-5748] Guava 32.1.1-jre

### PR DESCRIPTION
**Pull request by snuyanzin**

### CODE REVIEW

**Comment by richardantal** [comment]
I wonder if there is a reason why we don't go to the latest/greatest 32.1.1?

**Comment by snuyanzin** [comment]
the PR was created when only 32.0.0 was present, that's the reason
i will update it

**Comment by richardantal** [comment]
Looks good to me, Thank you Sergey for the change.
I don't have permissions to review, maybe @stoty does.

**Review by stoty — APPROVED** [review]
+1 LGTM

**Comment by snuyanzin** [comment]
Thanks for having a look and sorry for the delay

**Comment by snuyanzin** [comment]
rebased and squashed commits

**Pull request merged**
