### PR TITLE
CALCITE-3180: Bump httpclient from 4.5.6 to 4.5.9

### PR DESCRIPTION
**Pull request by Fokko**

### CODE REVIEW

**Comment by asereda-gs** [comment]
Pls add your full name in commit message. 
> CALCITE-3180: Bump httpclient from 4.5.6 to 4.5.9 (FirstName LastName)

**Comment by Fokko** [comment]
@asereda-gs Done!

**Comment by asereda-gs** [comment]
pls resolve the conflicts

**Comment by Fokko** [comment]
Done @asereda-gs

**Comment by asereda-gs** [comment]
@Fokko  there are still conflicts. 
Pls rebase against master to have single commit (and linear history).

Can you also change commit message to have jira id in brackets ? 
> [CALCITE-3180] Bump httpclient from 4.5.6 to 4.5.9 (Fokko Driesprong)

**Comment by Fokko** [comment]
@asereda-gs all done!

**Pull request merged**
