### PR TITLE
[CALCITE-5257] NVARCHAR is treated as "UNKNOWN TYPE" when searching Oracle

### PR DESCRIPTION
**Pull request by ILuffZhe**
Support NVARCHAR Type in Avatica when searching Oracle.

### CODE REVIEW

**Comment by rubenada** [comment]
@ILuffZhe could you please add a unit test for the problem?

**Comment by ILuffZhe** [comment]
@rubenada Hi, Ruben. I've added unit test for this case, please take a look when you have time.

**Comment by rubenada** [comment]
Thanks @ILuffZhe , lgtm.
Could you please squash commits into a single one?

**Comment by ILuffZhe** [comment]
Thanks for your review, @rubenada  I've squashed the commits.

**Pull request merged**
