### PR TITLE
CALCITE-2003 Remove global synchronization on openConnection

### PR DESCRIPTION
**Pull request by joshelser**

### CODE REVIEW

**Comment by joshelser** [comment]
@julianhyde might you know why Travis is killing the maven build after just a couple of minutes? Maybe I'm missing some more configuration?

https://travis-ci.org/apache/calcite-avatica/builds/284317333

**Comment by julianhyde** [comment]
no idea. looks a bit like this: https://github.com/travis-ci/travis-ci/issues/8172

**Comment by risdenk** [comment]
@joshelser Did you see https://github.com/apache/calcite/pull/542? Any chance it is a surefire issue?

**Comment by joshelser** [comment]
@risdenk no, I did miss that one! Let me try that quick. Otherwise, I'll just leave the privileged=true tweak on since that "worked"

**Comment by joshelser** [comment]
Ok, that is unrelated. We only have the failsafe-plugin configured to do parallel tests in Avatica, not surefire-plugin too. Thanks for the suggestion though, Kevin!

As I understand it, doing the `sudo: required` just increases the amount of time it takes for tests to start running (the things it actually provides aren't needed for Avatica). Given the relative low-velocity of commits to Avatica, I think that's a fine tradeoff for stable test reports.

**Pull request closed without merging**
