### PR TITLE
[CALCITE-5374] Upgrade jackson from 2.10.0 to 2.14.1

### PR DESCRIPTION
**Pull request by snuyanzin**
The PR upgrading jackson to 2.14.0

### CODE REVIEW

**Comment by F21** [comment]
@snuyanzin Can you please take a look at the failing tests for JDK8?

**Comment by snuyanzin** [comment]
It seems the reason is that in 2.14.0 `com.fasterxml.jackson.databind.node.ObjectNode#with` became deprecated https://github.com/FasterXML/jackson-databind/issues/3568
So first need to update it in Calcite and replace deprecated methods and then could be updated for Avatica.

**Comment by julianhyde** [comment]
Now I've merged the fix into Calcite, the Avatica JDK 8 test should pass. Once it passes let's merge this PR.

**Comment by snuyanzin** [comment]
Thanks for merging.
If you don't mind i would update it to 2.14.1 to include fix for [ObjectMapper default heap consumption increased significantly from 2.13.x to 2.14.0 ](https://github.com/FasterXML/jackson-databind/issues/3665)

I will try to upgrade both Calcite and Avatica today

**Review by F21 — APPROVED** [review]
LGTM!

**Pull request closed without merging**
