### PR TITLE
[CALCITE-2972] Upgrade jetty to 9.4.15.v20190215

### PR DESCRIPTION
**Pull request by risdenk**
Upgrade jetty to 9.4.15.v20190215 and add suppressions for deprecations associated with the upgrade.

### CODE REVIEW

**Comment by risdenk** [comment]
Well apparently this isn't so simple either :(

On IBM Java the follow errors occurred. I have not tried to track them down yet.

```
[[1;31mERROR[m] [1;31mTests [0;1mrun: [0;1m2[m, Failures: 0, [1;31mErrors: [0;1;31m2[m, Skipped: 0, Time elapsed: 1.76 s[1;31m <<< FAILURE![m - in org.apache.calcite.avatica.[1mSslDriverTest[m
[[1;31mERROR[m] testReadWrite[0](org.apache.calcite.avatica.SslDriverTest)  Time elapsed: 0.089 s  <<< ERROR!
java.lang.RuntimeException: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at org.apache.calcite.avatica.SslDriverTest.testReadWrite(SslDriverTest.java:137)
Caused by: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at org.apache.calcite.avatica.SslDriverTest.testReadWrite(SslDriverTest.java:137)

[[1;31mERROR[m] testReadWrite[1](org.apache.calcite.avatica.SslDriverTest)  Time elapsed: 0.037 s  <<< ERROR!
java.lang.RuntimeException: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at org.apache.calcite.avatica.SslDriverTest.testReadWrite(SslDriverTest.java:137)
Caused by: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at org.apache.calcite.avatica.SslDriverTest.testReadWrite(SslDriverTest.java:137)
```

**Comment by joshelser** [comment]
Our custom SpnegoLoginService is no concern on this upgrade. Specifically, we can see no changes made to SpnegoLoginService, specifically around the field we're setting via reflection: `_targetName` in our hack class. Additionally, the OID addition we're doing for krb5 and spnego seems necessary -- I suspect no one picked up my thread when I tried to fix that in jetty.

**Comment by joshelser** [comment]
For the IBM jdk stuff, I bet it's a TLS protocol mismatch. If you look a little farther up in the console log:
```
2019-04-03 14:40:04,000 [main] WARN  - No supported ciphers from [SSL_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, SSL_ECDHE_RSA_WITH_AES_256_CBC_SHA384, SSL_RSA_WITH_AES_256_CBC_SHA256, SSL_ECDH_ECDSA_WITH_AES_256_CBC_SHA384, SSL_ECDH_RSA_WITH_AES_256_CBC_SHA384, SSL_DHE_RSA_WITH_AES_256_CBC_SHA256, SSL_DHE_DSS_WITH_AES_256_CBC_SHA256, SSL_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, SSL_ECDHE_RSA_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_AES_256_CBC_SHA, SSL_ECDH_ECDSA_WITH_AES_256_CBC_SHA, SSL_ECDH_RSA_WITH_AES_256_CBC_SHA, SSL_DHE_RSA_WITH_AES_256_CBC_SHA, SSL_DHE_DSS_WITH_AES_256_CBC_SHA, SSL_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, SSL_ECDHE_RSA_WITH_AES_128_CBC_SHA256, SSL_RSA_WITH_AES_128_CBC_SHA256, SSL_ECDH_ECDSA_WITH_AES_128_CBC_SHA256, SSL_ECDH_RSA_WITH_AES_128_CBC_SHA256, SSL_DHE_RSA_WITH_AES_128_CBC_SHA256, SSL_DHE_DSS_WITH_AES_128_CBC_SHA256, SSL_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, SSL_ECDHE_RSA_WITH_AES_128_CBC_SHA, SSL_RSA_WITH_AES_128_CBC_SHA, SSL_ECDH_ECDSA_WITH_AES_128_CBC_SHA, SSL_ECDH_RSA_WITH_AES_128_CBC_SHA, SSL_DHE_RSA_WITH_AES_128_CBC_SHA, SSL_DHE_DSS_WITH_AES_128_CBC_SHA, SSL_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, SSL_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, SSL_ECDHE_RSA_WITH_AES_256_GCM_SHA384, SSL_RSA_WITH_AES_256_GCM_SHA384, SSL_ECDH_ECDSA_WITH_AES_256_GCM_SHA384, SSL_ECDH_RSA_WITH_AES_256_GCM_SHA384, SSL_DHE_DSS_WITH_AES_256_GCM_SHA384, SSL_DHE_RSA_WITH_AES_256_GCM_SHA384, SSL_ECDHE_RSA_WITH_AES_128_GCM_SHA256, SSL_RSA_WITH_AES_128_GCM_SHA256, SSL_ECDH_ECDSA_WITH_AES_128_GCM_SHA256, SSL_ECDH_RSA_WITH_AES_128_GCM_SHA256, SSL_DHE_RSA_WITH_AES_128_GCM_SHA256, SSL_DHE_DSS_WITH_AES_128_GCM_SHA256]
```
Was reading through https://github.com/cloudant/java-cloudant/issues/215 which is what lead me to wonder..

**Comment by risdenk** [comment]
@joshelser - thanks for the pointer on IBM Java. Looks like the Jetty change to ciphers is here: https://github.com/eclipse/jetty.project/issues/2807 Some details about IBM java and the change here: https://github.com/eclipse/jetty.project/issues/2921

As far as removing deprecating changes - see https://github.com/apache/calcite-avatica/pull/92 and the issues I ran into :/ Jetty took up the OID changes recently. This PR is mostly just to get the upgrade in and not worry about the deprecating removal stuff.

**Comment by joshelser** [comment]
Ah ok. Sorry. I didn't realize there were two pulls you had open :)

**Comment by risdenk** [comment]
Ok so bad news - 

IBM uses `SSL_*` for all the ciphers. Oracle uses `TLS_*` for newer ciphers. Jetty 9.4.12+ excluded all `SSL_*` ciphers due to insecurities. No way to override IBM to use the `TLS_*` standard naming. Names are interchangeable but excluding `SSL_*` means not in cipher list.
* https://www.ibm.com/support/knowledgecenter/en/SSYKE2_7.0.0/com.ibm.java.security.component.70.doc/security-component/jsse2Docs/ciphersuites.html
* https://www.ibm.com/developerworks/community/forums/html/threadTopic?id=9b5a56a9-fa46-4031-b33b-df91e28d77c2

Finally more bad news... Currently cipher suites aren't configurable - see CALCITE-1480

**Comment by risdenk** [comment]
Added skip of IBM java on `SslDriverTest` due to eclipse/jetty.project#2807 and eclipse/jetty.project#2807

**Pull request merged**
