### PR TITLE
[CALCITE-6697] Update Scott-data-hsqldb from 0.1 to 0.2 in Avatica

### PR DESCRIPTION
**Pull request by caicancai**
https://issues.apache.org/jira/browse/CALCITE-6697

### CODE REVIEW

**Comment by stoty** [comment]
The test failures look related.
Maybe hsqldb.version also needs to be synced ?

**Comment by caicancai** [comment]
> The test failures look related. Maybe hsqldb.version also needs to be synced ?

I'll try it later, thanks for the reminder

**Comment by caicancai** [comment]
@stoty It looks like some of the data in the test set has been transformed. I’m not sure whether to continue this work. Do you have any suggestions?

**Comment by stoty** [comment]
Is the hsql update a security issue ?
If not, I'd just leave it alone, it's only used for tests.

Otherwise, all the tests using the dataset and hsql would need to be checked and updated to work with the new HSQL and test data.

**Pull request closed without merging**
