### PR TITLE
[CALCITE-4900] NullPointerException when send ExectuteRequest via protobuf with no parameters

### PR DESCRIPTION
**Pull request by Logioniz**
NullPointerException when send ExectuteRequest via protobuf with no parameters

### CODE REVIEW

**Comment by NobiGo** [comment]
@Logioniz Please add unit test for this? Looks like a bug which can reproduce.

**Comment by Logioniz** [comment]
@NobiGo done.

**Comment by Logioniz** [comment]
@NobiGo can I do something else or is everything done and are we waiting for something?

**Comment by NobiGo** [comment]
@Logioniz Hi， We never make commit info start with a Fixed bug... Just describe the ISSUE enough(same as JIRA summary).

**Comment by Logioniz** [comment]
@NobiGo, ok, i'm squash commits to one and reword commit message.

Is there anything else I can do to help?

**Comment by NobiGo** [comment]
@Logioniz Please 
1）resolve the pending comment.
2）change the PR commit info meantime.
3）Before the final review, Please don't rebase the commits.

**Comment by Logioniz** [comment]
@NobiGo is it ok now?

**Comment by rubenada** [comment]
Thanks @Logioniz for the PR.

@NobiGo the PR seems in a good shape. Do you have any further comments? Otherwise I'll merge it in the coming days.

**Pull request merged**
