### PR TITLE
[CALCITE-4962] Protobuf debug does not show request/response type

### PR DESCRIPTION
**Pull request by marcobjorge**
Add request/response type to the protobuf debug messages so that it's possible to debug and understand problems in the protocol with clients.

### CODE REVIEW

**Review by NobiGo — APPROVED** [review]
LGTM

**Comment by NobiGo** [comment]
@marcobjorge  The Commit Info should be the same as the Jira summary.

**Comment by marcobjorge** [comment]
> @marcobjorge The Commit Info should be the same as the Jira summary.

As per your request matched the commit title to the Jira summary.

**Comment by marcobjorge** [comment]
@NobiGo , anything else I should do to get this merged?

**Pull request merged**
