### PR TITLE
[CALCITE-5812] Fix failing ./gradlew tasks

### PR DESCRIPTION
**Pull request by richardantal**

### CODE REVIEW

**Comment by richardantal** [comment]
@zabetak @snuyanzin Can you please review this change?

**Review by zabetak — APPROVED** [review]
LGTM, thanks for the PR!

Can you please also add `tasks` in a few CI runs as it was done in the calcite repo so that we can catch such problems earlier.

**Comment by richardantal** [comment]
Sure, I added tasks to a few CI run and rebased the change to the upstream/main .

**Comment by richardantal** [comment]
Thank you for the review and for merging the change.

**Pull request closed without merging**
