### PR TITLE
CALCITE-5009 Transparent JDBC connection re-creation may lead to data…

### PR DESCRIPTION
**Pull request by stoty**
… loss

Change-Id: Iaf10b6e4d4760cce9a7fabf1762a94501684f23d

### CODE REVIEW

**Comment by stoty** [comment]
I don't think that the checkstyle/rat errors are related to this patch.

**Comment by F21** [comment]
I've fixed the build, you should be able to rebase on top of master to get the tests passing.

**Comment by stoty** [comment]
thank you @F21.

**Review by joshelser — APPROVED** [review]
I was going to suggest that we also update https://github.com/apache/calcite-avatica/blob/master/site/_docs/client_reference.md but I see that it's already out of date. We can merge this change and then go back and make sure the client_reference.md page is updated for all of the user-facing configuration properties (maybe adding the client retries property there, too).

**Pull request merged**
