### PR TITLE
[CALCITE-2352] Update to checkstyle 6.18

### PR DESCRIPTION
**Pull request by laurentgo**
Update project to maven-checkstyle-plugin 3.0.0/checkstyle 6.18.
Fix all new reported violations.

### CODE REVIEW

**Comment by risdenk** [comment]
Changes look reasonable at a glance. Are there any compatibility issues with changing the method signatures? I can run a check on this if that helps.

**Comment by laurentgo** [comment]
From a public API perspective, there should not be: checkstyle only complains if constructor has a greater visibility than the class itself. The only exception has been the factory which is accessed through reflection (and the code assumes the constructor is public)

**Comment by laurentgo** [comment]
Thanks for the check! unless any objection, I'll merge it tomorrow (cc @F21 )!

**Comment by laurentgo** [comment]
Merged in acb675de97b9b0743c09368820a770e2ceda05f8

**Pull request closed without merging**
