### PR TITLE
[CALCITE-6530] HTTP Sessions are never expired in Avatica server

### PR DESCRIPTION
**Pull request by stoty**

### CODE REVIEW

**Review by joshelser — APPROVED** [review]
Was reading a stackoverflow post and it looks like Jetty defaults this to 30mins when using their web descriptor (which Avatica isn't): https://stackoverflow.com/questions/49300484/how-to-set-the-http-session-timeout-in-jetty-9-embedded

Looks good to me (but I am distant from the codebase). I can't imagine that this needs to be user-configurable, either.

**Comment by stoty** [comment]
I have read the same article :)
Yes, I came to the same conclusion regarding the web descriptor and the default idle timeout.

**Comment by stoty** [comment]
Thanks for the quick reply Josh.

**Comment by joshelser** [comment]
> I have read the same article :) Yes, I came to the same conclusion regarding the web descriptor and the default idle timeout.

Excellent, I figured as much!

> Thanks for the quick reply Josh.

You bet, caught me at a good time and this change looked straightforward 👍🏼

**Pull request merged**
