### PR TITLE
CALCITE-2022 add dynamic drive calculation in case of Windows

### PR DESCRIPTION
**Pull request by snuyanzin**
test fixed in case non "C" drive in Windows

### CODE REVIEW

**Comment by joshelser** [comment]
@snuyanzin thanks for the change. Have you tested this on Windows?

**Comment by snuyanzin** [comment]
yes, before fix it failed like 
```
java.lang.AssertionError: 
Expected: is "C:\my\truststore.jks"
     but: was "D:\my\truststore.jks"
Expected :C:\my\truststore.jks
Actual   :D:\my\truststore.jks
```

	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at org.apache.calcite.avatica.ConnectionConfigImplTest.testTrustStore(ConnectionConfigImplTest.java:42)

**Comment by joshelser** [comment]
Perfect, thanks for the fix, @snuyanzin!

FYI @F21. I'd pull this over to branch-avatica-1.12, but I see you have already updated it in prep for the release.  Don't want to mess you up :)

**Comment by F21** [comment]
Thanks for merging! I'll update rebase the release branch.

**Pull request closed without merging**
