### PR TITLE
[CALCITE-2412][Avatica] appveyor.yml for Windows CI (Appveyor)

### PR DESCRIPTION
**Pull request by snuyanzin**
[CALCITE-2412][Avatica] appveyor.yml for Windows CI (Appveyor)

### CODE REVIEW

**Comment by F21** [comment]
Hey @snuyanzin , I wanted to see if it's possible to merge this PR for avatica 1.13.0. Would you be able to rebase against master?

**Comment by snuyanzin** [comment]
I think it is possible as the PR contains only a new file which is not present in master => no conflicts should be observed.
Anyway I did rebase against master and also enabled jdk9/jdk10 for appveyor build (unfortunately it still does not support jdk11, jdk12).

If it is possible besides the merging of the PR it would be great to have turned on Avatica appveoyr built on commit with its own badge. I think I do not have rights to do it but I did it for my own fork.

By the way here it is the link to the last appveyor build related to this issue
https://ci.appveyor.com/project/snuyanzin/calcite-avatica

**Comment by F21** [comment]
@snuyanzin Thanks for looking at this! I've asked infra to enable Appveyfor for the repo: https://issues.apache.org/jira/browse/INFRA-17249.

Once enabled, infra should give us a link to the appveyor build page.

Can you also squash your commits and rename the commit message to `[CALCITE-2412] ...commit message here...?

**Comment by snuyanzin** [comment]
Squashed commits and changed commit message
Please let me know if it is ok or not

**Comment by F21** [comment]
Thanks @snuyanzin ! That looks great! When infra enables appveyor (they should post a reply in [INFRA-17249](https://issues.apache.org/jira/browse/INFRA-17249)), can you add the badge to the readme and squash again? Then just merge the PR as everything else looks good to me 👍

**Comment by snuyanzin** [comment]
> When infra enables appveyor (they should post a reply in INFRA-17249), can you add the badge to the readme and squash again?

Yes, sure. Have just become a watcher in the mentioned ticket. As soon as the url to Appveyor Avatica project will be published I will add the badge to the readme and squash.

**Comment by snuyanzin** [comment]
Squashed, rebased.
Added badge.
Added `-DskipDockerCheck` because of CALCITE-2385
Looks like working https://ci.appveyor.com/project/ApacheSoftwareFoundation/calcite-avatica/builds/20397074.

Currently it shows failing status as it points to master and changes are not merged I think.

**Comment by F21** [comment]
Thank you @snuyanzin ! Looks great! Please merge when you have the chance to do it 😄

**Pull request closed without merging**
